{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  sops = {
    secrets = {
      "homepage-dashboard-env" = {};
    };
  };

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;
  
  systemd.services.homepage-dashboard = {
    environment.HOMEPAGE_CONFIG_DIR = "/var/lib/homepage-dashboard";
    serviceConfig = {
      WorkingDirectory = "/var/lib/homepage-dashboard";
      StateDirectory = "homepage-dashboard";
    };
  };

  services.homepage-dashboard = {
    enable=true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.homepage-dashboard;
    # allowedHosts = "homepage.montybeta.org,localhost:8082,127.0.0.1:8082,192.168.86.177:8082";
    allowedHosts = "*";
    environmentFile = config.sops.secrets."homepage-dashboard-env".path;
      # Contains secrets for config as well as HOMEPAGE_CONFIG_DIR=/var/lib/homepage-dashboard
    openFirewall = true;
    widgets = [
      {
        logo = {
          icon = "https://1.bp.blogspot.com/-8pXESPi3igc/XoC5nUl5dcI/AAAAAAAAqwg/-iz6DADXKJQLoB78_Ri7g9637RlRZV2sgCLcBGAsYHQ/s1600/HomeLab_icon.png";
        };
      }
      {
        greeting = {
          text_size = "3xl";
          text = "Monty Casa Homelab";
        };
      }
      {
        resources = {
          cpu = true;
          memory = true;
          disk = "/";
        };
      }
      {
        search = {
          provider = "duckduckgo";
          target = "_blank";
        };
      }
    ];
    settings = {
      title = "Monty Casa Homelab";
      favicon = "https://1.bp.blogspot.com/-8pXESPi3igc/XoC5nUl5dcI/AAAAAAAAqwg/-iz6DADXKJQLoB78_Ri7g9637RlRZV2sgCLcBGAsYHQ/s1600/HomeLab_icon.png";
      quicklaunch = {
        searchDescriptions = true;
        hideInternetSearch = true;
        hideVisitURL = true;
      };
      providers = {
        openweathermap = "openweathermapapikey";
        weatherapi = "weatherapiapikey";
      };
      layout = {
        Proxmox = {
          tab = "Machines";
        };
        Storage = {
          tab = "Machines";
        };
        "Other Machines" = {
          tab = "Machines";
        };
        Offsite = {
          tab = "Machines";
        };
        "Routers, DNS, Switches" = {
          tab = "Networking";
        };
        "Access Points" = {
          tab = "Networking";
        };
        "Remote Access" = {
          tab = "Networking";
        };
        "Home Automation" = {
          tab = "Home";
        };
        NVR = {
          tab = "Home";
        };
        "Media Servers" = {
          tab = "Media";
          style = "row";
          columns = 1;
        };
        Aar = {
          tab = "Media";
          style = "row";
          columns = 3;
        };
        Apps = {
          tab = "Apps";
          style = "row";
          columns = 3;
        };
        Status = {
          style = "row";
          columns = 2;
        };
      };
    };
    services = [
      {
        Status = [
          {
            "Uptime Kuma" = {
              href = "https://uptime.montycasa.net";
              siteMonitor = "https://uptime.montycasa.net";
              icon = "sh-uptime-kuma.svg";
              widget = {
                type = "uptimekuma";
                url = "https://uptime.montycasa.net";
                slug = "homepage";
              };
            };
          }
          {
            MySpeed = {
              href = "https://myspeed.montycasa.net";
              siteMonitor = "https://myspeed.montycasa.net";
              icon = "sh-myspeed.png";
              widget = {
                type = "myspeed";
                url = "https://myspeed.montycasa.net";
              };
            };
          }
          {
            Dockge = {
              href = "https://dockge.montycasa.net";
              siteMonitor = "https://dockge.montycasa.net";
              icon = "sh-dockge.svg";
            };
          }
          {
            Gotify = {
              href = "https://notify.montycasa.com";
              siteMonitor = "https://notify.montycasa.com";
              icon = "sh-gotify.svg";
            };
          }
        ];
      }
      {
        Proxmox = [
          {
            Stark = {
              href = "https://stark.montycasa.net";
              siteMonitor = "https://stark.montycasa.net";
              description = "Proxmox VE";
              icon = "sh-proxmox.svg";
              widget = {
                type = "proxmox";
                url = "https://stark.montycasa.net";
                username = "{{proxmox_username}}";
                password = "{{proxmox_password}}";
                node = "stark";
              };
            };
          }
          {
            Loki = {
              href = "https://loki.montycasa.net";
              siteMonitor = "https://loki.montycasa.net";
              description = "Proxmox VE";
              icon = "sh-proxmox.svg";
              widget = {
                type = "proxmox";
                url = "https://loki.montycasa.net";
                username = "{{proxmox_username}}";
                password = "{{proxmox_password}}";
                node = "loki";
              };
            };
          }
          {
            Starlord = {
              href = "https://starlord.montycasa.net";
              siteMonitor = "https://starlord.montycasa.net";
              description = "Proxmox VE";
              icon = "sh-proxmox.svg";
              widget = {
                type = "proxmox";
                url = "https://starlord.montycasa.net";
                username = "{{proxmox_username}}";
                password = "{{proxmox_password}}";
                node = "starlord";
              };
            };
          }
        ];
      }
      {
        Storage = [
          {
            "TrueNAS Home" = {
              href = "https://truenas.montycasa.net";
              siteMonitor = "https://truenas.montycasa.net";
              description = "TrueNAS Scale";
              icon = "sh-truenas-scale.svg";
              widget = {
                type = "truenas";
                url = "https://truenas.montycasa.net";
                username = "{{truenas_username}}";
                password = "{{truenas_password}}";
                nasType = "scale";
              };
            };
          }
          {
            "Proxmox Backup Server" = {
              href = "https://pbs.montycasa.net";
              siteMonitor = "https://pbs.montycasa.net";
              icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox-light.png";
              widget = {
                type = "proxmoxbackupserver";
                url = "https://pbs.montycasa.net";
                username = "{{pbs_username}}";
                password = "{{pbs_password}}";
              };
            };
          }
          {
            Syncthing = {
              href = "https://192.168.86.99:20910/";
              siteMonitor = "https://192.168.86.99:20910/";
              icon = "sh-syncthing.svg";
            };
          }
          {
            Backblaze = {
              href = "https://secure.backblaze.com/user_signin.htm";
              icon = "sh-backblaze.svg";
            };
          }
        ];
      }
      {
        "Other Machines" = [
          {
            PiKVM = {
              href = "https://pikvm.skink-galaxy.ts.net";
              siteMonitor = "https://pikvm.skink-galaxy.ts.net";
              icon = "https://avatars.githubusercontent.com/u/41749659?s=200&v=4";
            };
          }
          {
            "Yondu VS Code" = {
              href = "http://192.168.86.114:8680";
              siteMonitor = "http://192.168.86.114:8680";
              description = "VS Code Server for yondu server";
              icon = "https://cdn3.iconfinder.com/data/icons/marvel-avatars-flaticons/64/yondu-avangers-marvel-avatars-gartoon-marvel_avatars-hero-512.png";
            };
          }
        ];
      }
      {
        Offsite = [
          {
            Wakanda = {
              href = "https://wakanda.skink-galaxy.ts.net:8006/";
              siteMonitor = "https://wakanda.skink-galaxy.ts.net:8006/";
              description = "Offsite Proxmox VE";
              icon = "sh-proxmox.svg";
              widget = {
                type = "proxmox";
                url = "https://wakanda.skink-galaxy.ts.net:8006";
                username = "{{wakanda_username}}";
                password = "{{wakanda_password}}";
                node = "wakanda";
              };
            };
          }
          {
            "Bucky TrueNAS" = {
              href = "https://bucky.skink-galaxy.ts.net/";
              siteMonitor = "https://bucky.skink-galaxy.ts.net/";
              description = "Offsite TrueNAS Scale";
              icon = "sh-truenas-scale.svg";
              widget = {
                type = "truenas";
                url = "https://bucky.skink-galaxy.ts.net/";
                username = "{{bucky_username}}";
                password = "{{bucky_password}}";
                nasType = "scale";
              };
            };
          }
          {
            "Bucky Backup Link" = {
              href = "https://10.10.12.10";
              siteMonitor = "https://10.10.12.10";
              description = "Backup Link to Bucky";
              icon = "sh-truenas-scale.svg";
            };
          }
          {
            DigitalOcean = {
              href = "https://cloud.digitalocean.com/projects/8c2d35b4-ab76-4750-87db-4230144b4a44/resources?i=d4b54a";
              description = "DigitalOcean VPS";
              icon = "sh-digitalocean.svg";
            };
          }
          {
            Linode = {
              href = "https://cloud.linode.com/linodes";
              description = "Linode VPS";
              icon = "sh-linode.svg";
            };
          }
        ];
      }
      {
        "Routers, DNS, Switches" = [
          {
            OPNSense = {
              href = "https://router.montycasa.net";
              siteMonitor = "https://router.montycasa.net";
              description = "Router/Firewall";
              icon = "sh-opnsense.svg";
              widget = {
                type = "opnsense";
                url = "https://router.montycasa.net";
                username = "{{opnsense_username}}";
                password = "{{opnsense_password}}";
              };
            };
          }
          {
            "Adguard Home" = {
              href = "https://blocker.montycasa.net";
              siteMonitor = "https://blocker.montycasa.net";
              description = "Network DNS Adblocker";
              icon = "sh-adguard-home.svg";
              widget = {
                type = "adguard";
                url = "https://blocker.montycasa.net";
                username = "{{adguard_username}}";
                password = "{{adguard_password}}";
              };
            };
          }
          {
            "Homelab 10GbE Aggregate Switch" = {
              href = "http://192.168.86.2/";
              siteMonitor = "http://192.168.86.2";
              description = "8x10GbE SPF+";
              icon = "mdi-router-network";
            };
          }
          {
            "Homelab 2.5GbE Mini Switch" = {
              href = "http://192.168.86.3/";
              siteMonitor = "http://192.168.86.3";
              description = "2x10GbE SPF+ / 4x2.5GbE";
              icon = "mdi-router-network";
            };
          }
          {
            "Homelab 2.5GbE PoE Switch" = {
              href = "http://192.168.86.4/";
              siteMonitor = "http://192.168.86.4";
              description = "1x10GbE SPF+ / 8x2.5GbE PoE";
              icon = "mdi-router-network";
            };
          }
          {
            "Basement PoE Switch" = {
              href = "http://192.168.86.5/";
              siteMonitor = "http://192.168.86.5";
              description = "8x1GbE with 4x PoE";
              icon = "mdi-router-network";
            };
          }
        ];
      }
      {
        "Access Points" = [
          {
            Omada = {
              href = "https://omada.montycasa.net";
              siteMonitor = "https://omada.montycasa.net";
              description = "Omada Controller";
              icon = "sh-omada.svg";
              widget = {
                type = "omada";
                url = "https://omada.montycasa.net";
                username = "{{omada_username}}";
                password = "{{omada_password}}";
                site = "{{omada_site}}";
              };
            };
          }
          {
            "Homelab AP" = {
              href = "http://192.168.86.11/";
              siteMonitor = "http://192.168.86.11/";
              description = "TP-Link Omada EAP723";
              icon = "mdi-access-point-network";
            };
          }
          {
            "Kitchen AP" = {
              href = "http://192.168.86.13/";
              siteMonitor = "http://192.168.86.13/";
              description = "TP-Link Omada EAP723";
              icon = "mdi-access-point-network";
            };
          }
          {
            "Garage AP" = {
              href = "http://192.168.86.15/";
              siteMonitor = "http://192.168.86.15/";
              description = "TP-Link Omada EAP235-Wall";
              icon = "mdi-access-point-network";
            };
          }
        ];
      }
      {
        "Remote Access" = [
          {
            Pangolin = {
              href = "https://pangolin.montycasa.com";
              siteMonitor = "https://pangolin.montycasa.com";
              description = "Proxy and Authentication";
              icon = "sh-pangolin.svg";
            };
          }
          {
            Tailscale = {
              href = "https://login.tailscale.com/admin/machines";
              description = "Mesh VPN";
              icon = "sh-tailscale.svg";
            };
          }
          {
            Cloudflare = {
              href = "https://dash.cloudflare.com/login";
              description = "Domain Name and DNS Service";
              icon = "sh-cloudflare.svg";
            };
          }
        ];
      }
      {
        "Home Automation" = [
          {
            "Home Assistant" = {
              href = "http://192.168.86.100:8123";
              siteMonitor = "http://192.168.86.100:8123";
              description = "Home Automation System";
              icon = "sh-home-assistant.svg";
            };
          }
          {
            "WLED Patio" = {
              href = "http://192.168.10.19/";
              siteMonitor = "http://192.168.10.19/";
              description = "Patio wall lights";
              icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/wled.png";
            };
          }
          {
            "WLED Cabinets" = {
              href = "http://192.168.10.17/";
              siteMonitor = "http://192.168.10.17/";
              description = "Kitchen under cabinet lights";
              icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/wled.png";
            };
          }
        ];
      }
      {
        NVR = [
          {
            Frigate = {
              href = "https://frigate.montycasa.net";
              siteMonitor = "https://frigate.montycasa.net";
              description = "Network Video Recorder";
              icon = "sh-frigate.svg";
            };
          }
          {
            "Bella's Room" = {
              href = "http://192.168.10.51/";
              siteMonitor = "http://192.168.10.51/";
              description = "IP Camera";
              icon = "mdi-webcam";
            };
          }
          {
            "Girls's Room" = {
              href = "http://192.168.10.50/";
              siteMonitor = "http://192.168.10.50/";
              description = "IP Camera";
              icon = "mdi-webcam";
            };
          }
          {
            Nursery = {
              href = "http://192.168.10.52/";
              siteMonitor = "http://192.168.10.52/";
              description = "IP Camera";
              icon = "mdi-webcam";
            };
          }
          {
            "Front Door" = {
              href = "http://192.168.10.54/";
              siteMonitor = "http://192.168.10.54/";
              description = "IP Camera";
              icon = "mdi-cctv";
            };
          }
          {
            "Back Door" = {
              href = "http://192.168.10.53/";
              siteMonitor = "http://192.168.10.53/";
              description = "IP Camera";
              icon = "mdi-cctv";
            };
          }
        ];
      }
      {
        "Media Servers" = [
          {
            Jellyfin = {
              href = "https://watchit.montycasa.com";
              siteMonitor = "https://watchit.montycasa.com";
              description = "Movie and TV Show Library";
              icon = "sh-jellyfin.svg";
              widget = {
                type = "jellyfin";
                url = "https://watchit.montycasa.com";
                key = "{{jellyfin_key}}";
                enableNowPlaying = true;
                enableUser = true;
                showEpisodeNumber = true;
                expandOneStreamToTwoRows = false;
              };
            };
          }
          {
            Immich = {
              href = "https://photos.montycasa.com";
              siteMonitor = "https://photos.montycasa.com";
              description = "Photo Library";
              icon = "sh-immich.svg";
              widget = {
                type = "immich";
                url = "https://photos.montycasa.com";
                key = "{{immich_key}}";
                version = 2;
              };
            };
          }
          {
            Audiobookshelf = {
              href = "https://audiobooks.montycasa.com";
              siteMonitor = "https://audiobooks.montycasa.com";
              description = "Audiobook Library";
              icon = "sh-audiobookshelf.svg";
              widget = {
                type = "audiobookshelf";
                url = "https://audiobooks.montycasa.com";
                key = "{{audiobookshelf_key}}";
              };
            };
          }
        ];
      }
      {
        Aar = [
          {
            qBittorrent = {
              href = "https://qbittorrent.montycasa.net";
              siteMonitor = "https://qbittorrent.montycasa.net";
              icon = "sh-qbittorrent.svg";
              widget = {
                type = "qbittorrent";
                url = "https://qbittorrent.montycasa.net";
                username = "{{qbittorrent_username}}";
                password = "{{qbittorrent_password}}";
              };
            };
          }
          {
            Radarr = {
              href = "https://radarr.montycasa.net";
              siteMonitor = "https://radarr.montycasa.net";
              icon = "sh-radarr.svg";
              widget = {
                type = "radarr";
                url = "https://radarr.montycasa.net";
                key = "{{radarr_key}}";
                enableQueue = true;
              };
            };
          }
          {
            Sonarr = {
              href = "https://sonarr.montycasa.net";
              siteMonitor = "https://sonarr.montycasa.net";
              icon = "sh-sonarr.svg";
              widget = {
                type = "sonarr";
                url = "https://sonarr.montycasa.net";
                key = "{{sonarr_key}}";
                enableQueue = true;
              };
            };
          }
          {
            Bazarr = {
              href = "https://bazarr.montycasa.net";
              siteMonitor = "https://bazarr.montycasa.net";
              icon = "sh-bazarr.png";
              widget = {
                type = "bazarr";
                url = "https://bazarr.montycasa.net";
                key = "{{bazarr_key}}";
              };
            };
          }
          {
            Prowlarr = {
              href = "https://prowlarr.montycasa.net";
              siteMonitor = "https://prowlarr.montycasa.net";
              icon = "sh-prowlarr.svg";
              widget = {
                type = "prowlarr";
                url = "https://prowlarr.montycasa.net";
                key = "{{prowlarr_key}}";
              };
            };
          }
          {
            Pinchflat = {
              href = "http://192.168.86.114:8945";
              siteMonitor = "http://192.168.86.114:8945";
              icon = "sh-pinchflat.png";
            };
          }
          {
            Transmission = {
              href = "http://192.168.86.114:9092/";
              siteMonitor = "http://192.168.86.114:9092/";
              description = "NO VPN";
              icon = "sh-transmission.svg";
              widget = {
                type = "transmission";
                url = "http://192.168.86.114:9092";
                username = "";
                password = "{{transmission_key}}";
                rpcUrl = "/transmission/";
              };
            };
          }
          {
            Jackett = {
              href = "http://192.168.86.114:9117/";
              siteMonitor = "http://192.168.86.114:9117/";
              description = "NO VPN";
              icon = "sh-jackett.svg";
              widget = {
                type = "jackett";
                url = "http://192.168.86.114:9117";
              };
            };
          }
        ];
      }
      {
        Apps = [
          {
            Nextcloud = {
              href = "https://drive.montycasa.com";
              siteMonitor = "https://drive.montycasa.com";
              icon = "sh-nextcloud.png";
            };
          }
          {
            Forgejo = {
              href = "https://git.montycasa.net";
              siteMonitor = "https://git.montycasa.net";
              icon = "sh-forgejo.svg";
            };
          }
          {
            "Alby Hub" = {
              href = "https://ln.montybitcoin.com";
              siteMonitor = "https://ln.montybitcoin.com";
              icon = "si-alby";
            };
          }
          {
            Karakeep = {
              href = "https://keep.montycasa.com";
              siteMonitor = "https://keep.montycasa.com";
              icon = "sh-karakeep.svg";
            };
          }
          {
            Paperless-ngx = {
              href = "https://paperless-ngx.montycasa.net";
              siteMonitor = "https://paperless-ngx.montycasa.net";
              icon = "sh-paperless-ngx.svg";
            };
          }
          {
            Mealie = {
              href = "https://mealie.montycasa.com";
              siteMonitor = "https://mealie.montycasa.com";
              icon = "sh-mealie.svg";
            };
          }
          {
            Endurain = {
              href = "https://fit.montycasa.com";
              siteMonitor = "https://fit.montycasa.com";
              icon = "sh-endurain.svg";
            };
          }
          {
            PocketID = {
              href = "https://auth.montycasa.com";
              siteMonitor = "https://auth.montycasa.com";
              icon = "sh-pocket-id.svg";
            };
          }
        ];
      }
    ];
  };

  # networking.firewall.allowedTCPPorts = [ 8082 ];
  

  system.stateVersion = "25.05";
}
