{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # Import immich-kiosk module from unstable
    "${inputs.nixpkgs-unstable}/nixos/modules/services/web-apps/immich-kiosk.nix"
  ];

  extra-services.tailscale = {
    enable = true;
    userspace-networking = true;
  };

  # sops secrets configuration
  sops.secrets."immich-secrets" = {
    owner = "immich";
    group = "immich";
    mode = "0400";
  };

  sops.secrets."immich-kiosk-api-key" = { };

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  extra-services.mount_home_media.enable = true;

  # # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /mnt/home_media 0755 root root -"
    "Z /mnt/home_media/immich 0750 immich immich -"
  ];

  # Immich service configuration
  services.immich = {
    enable = true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.immich;
    host = "0.0.0.0";
    # port = 2283;
    openFirewall = true;
    mediaLocation = "/mnt/home_media/immich";
    accelerationDevices = [ "/dev/dri" ];
    secretsFile = config.sops.secrets."immich-secrets".path;
    environment = {
      TZ = "America/New_York";
    };
    settings = {
      #server.externalDomain = "";
      newVersionCheck.enabled = true;
    };

    database = {
      enable = true;
      createDB = true;
    };
  };

  # Add immich user to video and render groups for hardware acceleration
  users.users.immich.extraGroups = [ "video" "render" ];

  # Enable hardware acceleration support
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      intel-vaapi-driver
      libva-vdpau-driver
      libvdpau-va-gl
    ];
  };

  # Immich Kiosk - slideshow display service
  services.immich-kiosk = {
    enable = true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.immich-kiosk;
    openFirewall = true;
    settings = {
      immich_url = "http://localhost:2283";
      immich_api_key._secret = "/run/secrets/immich-kiosk-api-key";
      show_time = true;
      time_format = 12; # 12 or 24
      show_date = true;
      date_format = "M/D/YYYY";
      clock_source = "client";
      people = [
        "9ba3b270-1d31-4a66-88f1-7747c81e68de" #First
        "ae264d67-95e1-4d15-bc67-c7aecc2cb890" #Second
        "928fda10-ab8f-47aa-a9e6-db6b9d5cb81b" #Third
        "b737f3d1-ffff-4731-8644-3a30c8d8a9d2" #Fourth
        "67da8aa8-17be-40f6-a7e8-6135aa188572" #Dog
      ];
      # memories =  true;
      layout = "splitview";
      show_image_date = true;
      image_date_format = "M/D/YYYY";
      show_image_location = true;
    };
  };

  networking.firewall.allowedTCPPorts = [ 2283 ];

  system.stateVersion = "25.11";
}