{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Enable virtualisation for containers
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /var/lib/endurain 0755 root root -"
    "d /var/lib/endurain/postgresql 0700 999 999 -"
    "d /var/lib/endurain/backend 0755 1000 1000 -"
    "d /var/lib/endurain/backend/logs 0755 1000 1000 -"
    "d /var/lib/endurain/backend/data 0755 1000 1000 -"
  ];

  # sops secrets configuration
  sops.secrets."endurain-env" = {
    # sopsFile = ../../secrets/secrets.yaml;
    owner = "root";
    group = "root";
    mode = "0400";
  };

  # FIXED: Create network before containers start
  systemd.services.init-endurain-network = {
    description = "Create the network for Endurain";
    after = [ "network.target" "podman.service" ];
    requires = [ "podman.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      ${pkgs.podman}/bin/podman network inspect endurain-net >/dev/null 2>&1 || \
      ${pkgs.podman}/bin/podman network create endurain-net
    '';
    before = [ 
      "podman-endurain-db.service"
      "podman-endurain.service"
    ];
  };

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      endurain-db = {
        image = "docker.io/postgres:17.5";
        autoStart = true;
        environmentFiles = [
          config.sops.secrets."endurain-env".path
          # DB_HOST
          # DB_PASSWORD
          # POSTGRES_PASSWORD
          # SECRET_KEY
          # FERNET_KEY
          # TZ=
          # ENDURAIN_HOST
          # BEHIND_PROXY
          # POSTGRES_DB
          # POSTGRES_USER
          # PGDATA
        ];
        volumes = [
          "/var/lib/endurain/postgresql:/var/lib/postgresql/data"
        ];
        extraOptions = [
          "--network=endurain-net"
          "--health-cmd=pg_isready -U endurain"
          "--health-interval=10s"
          "--health-timeout=5s"
          "--health-retries=5"
          "--health-start-period=10s"
        ];
      };
      
      endurain = {
        image = "ghcr.io/joaovitoriasilva/endurain:latest";
        autoStart = true;
        dependsOn = [ "endurain-db" ];
        ports = [
          "8080:8080"
        ];
        environmentFiles = [
          config.sops.secrets."endurain-env".path
        ];
        volumes = [
          "/var/lib/endurain/backend/data:/app/backend/data"
          "/var/lib/endurain/backend/logs:/app/backend/logs"
        ];
        extraOptions = [
          "--network=endurain-net"
        ];
      };
    };
  };

  # networking.firewall.allowedTCPPorts = [ 8080 ];
  networking.firewall.enable = false;

  system.stateVersion = "25.05";
}