{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    inputs.nixpkgs-unstable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.jellyfin
    # pkgs.jellyfin
    pkgs.jellyfin-web
    pkgs.jellyfin-ffmpeg
    intel-gpu-tools
  ];

  # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /mnt/media 0750 jellyfin jellyfin -"
    "d /mnt/home_media 0750 jellyfin jellyfin -"
  ];

  extra-services.mount_media = {
    enable = true;
    readOnly = true;
  };
  extra-services.mount_home_media = {
    enable = true;
    readOnly = true;
  };

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;
  
  services.openssh.enable = true;

  services.jellyfin = {
    enable = true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.jellyfin;
    openFirewall = true;
  };

  hardware.intelGpu = {
    enable = true;
    users = [ "jellyfin" ];
    videoAccess = true;
    computeRuntime = true;
    videoProcessing = true;
  };

  nixpkgs.config.packageOverrides = pkgs: {  
    intel-vaapi-driver = pkgs.intel-vaapi-driver.override { enableHybridCodec = true; };
  };
  # Set the VAAPI driver to use the newer iHD driver
  systemd.services.jellyfin.environment.LIBVA_DRIVER_NAME = "iHD";
  environment.sessionVariables = { LIBVA_DRIVER_NAME = "iHD"; };
  
  networking.firewall.allowedTCPPorts = [ 8096 ];

  system.stateVersion = "25.05";
}
