{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  networking.hostName = "mattermost";

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  services.openssh.enable = true;

  services.mattermost = {
    enable = true;
    siteUrl = "https://chat.montycasa.com"; # no trailing slash (module asserts this)
    siteName = "Monty Chat";
    host = "0.0.0.0"; # listen on the tailnet, not just loopback
    port = 8065;

    # Auto-provision a local PostgreSQL database. peerAuth auto-enables for
    # stateVersion >= 25.05 with database.host = "localhost", so this fresh
    # 25.11 host gets it for free — no DB password/secret to manage.
    database.create = true;

    # Keep config.json declarative. Enable bot accounts (for the hermes bot
    # token) and personal access tokens. Local email/password login only;
    # OIDC/SAML SSO is Mattermost Enterprise-only.
    mutableConfig = false;
    settings = {
      ServiceSettings = {
        EnableBotAccountCreation = true;
        EnablePersonalAccessTokens = true;
      };
    };
  };

  networking.firewall.allowedTCPPorts = [ 8065 ];

  system.stateVersion = "25.11";
}
