{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };

  # sops secrets configuration
  sops.secrets."nextcloud-admin-password" = {
    owner = "nextcloud";
    group = "nextcloud";
    mode = "0400";
  };
  sops.secrets."nextcloud-secret-file" = {
    owner = "nextcloud";
    group = "nextcloud";
    mode = "0400";
  };
  sops.secrets."nextcloud-db-password" = {
    owner = "nextcloud";
    group = "nextcloud";
    mode = "0400";
  };

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /mnt/drive 0750 nextcloud nextcloud -"
  ];

  # optional, but ensures rpc-statsd is running for on demand mounting
  # boot.supportedFilesystems = [ "nfs" ];

  fileSystems."/mnt/drive" = {
    device = "192.168.86.99:/mnt/HDD-Mirror-01/drive";
    fsType = "nfs";
    options = [
      "noatime"
      "rsize=8192"
      "wsize=8192"
      "_netdev"
    ];
  };
     
  services.nextcloud = {
    enable = true;
    hostName = "drive.montycasa.net";
    datadir = "/mnt/drive";
    # Need to manually increment with every major upgrade.
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.nextcloud32;
    # Let NixOS install and configure the database automatically.
    database.createLocally = true;
    # Let NixOS install and configure Redis caching automatically.
    configureRedis = true;
    # Increase the maximum file upload size.
    maxUploadSize = "16G";
    https = true;
    autoUpdateApps.enable = true;
    extraAppsEnable = true;
    extraApps = with config.services.nextcloud.package.packages.apps; {
      # List of apps we want to install and are already packaged in
      # https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/nextcloud/packages/nextcloud-apps.json
      inherit calendar contacts notes onlyoffice;
      # Custom app example.
      # socialsharing_telegram = pkgs.fetchNextcloudApp rec {
      #   url =
      #     "https://github.com/nextcloud-releases/socialsharing/releases/download/v3.0.1/socialsharing_telegram-v3.0.1.tar.gz";
      #   license = "agpl3";
      #   sha256 = "sha256-8XyOslMmzxmX2QsVzYzIJKNw6rVWJ7uDhU1jaKJ0Q8k=";
      # };
    };
    secretFile = config.sops.secrets."nextcloud-secret-file".path;
      # passwordsalt
    settings = {
      overwriteProtocol = "https";
      default_phone_region = "US";
      overwritehost = "drive.montycasa.net";
      trusted_proxies = [ "147.182.139.226" ];
      # trusted_domains = ["192.168.86.136"];
    };
    config = {
      dbtype = "pgsql";
      adminuser = "patrick";
      adminpassFile = config.sops.secrets."nextcloud-admin-password".path;
    };
    # Suggested by Nextcloud's health check.
    phpOptions."opcache.interned_strings_buffer" = "16";
  };

  networking.firewall.allowedTCPPorts = [ 80 ];

  system.stateVersion = "25.05";
}