{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  extra-services.tailscale = {
    enable = true;
    userspace-networking = true;
  };

  sops = {
      # defaultSopsFile = ../../../secrets/secrets.yaml;
      secrets = {
        "grist-env" = {};
      };
    };

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Enable virtualisation for containers
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /var/lib/grist 0755 root root -"
    "d /var/lib/grist/persist 0755 root root -"
  ];

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      grist = {
        image = "gristlabs/grist:latest";
        autoStart = true;
        ports = [
          "8484:8484"
        ];
        extraOptions = [
          "--pull=always"
        ];
        volumes = [
          "/var/lib/grist/persist:/persist"
        ];
        environmentFiles = [
          config.sops.secrets."grist-env".path
          # GRIST_DEFAULT_EMAIL
          # GRIST_SESSION_SECRET
        ];
      };
    };
  };

  networking.firewall.allowedTCPPorts = [ 8484 ];

  system.stateVersion = "25.05";
}