{ pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    ../../users/patrick
    
  ];
	
  environment.systemPackages = with pkgs; [
		ansible
    ansible-lint
    terraform
    sshpass
    lazygit

    # This is required for the ansibleguy.opnsense ansible role
    (python3.withPackages (ps: with ps; [
      httpx
    ]))
  ];

  boot.initrd = { supportedFilesystems = [ "nfs" ];
  kernelModules = [ "nfs" ];
  };
  nixpkgs.config.allowUnfree = true;

  fileSystems."/mnt/home_media" = {
    device = "192.168.86.99:/mnt/HDD-Mirror-01/home_media";
    fsType = "nfs";
  };

  # List services that you want to enable:

  extra-services.tailscale.enable = true;
  extra-services.tmux.enable = true;

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  system.stateVersion = "24.05";
}
