{ pkgs, config, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    ../../users/patrick/hosts/nix-fury
    # ../../secrets
  ];
	
  environment.systemPackages = with pkgs; [
		ansible
    ansible-lint
    terraform
    sshpass
    lazygit

    # This is required for the ansibleguy.opnsense ansible role
    (python3.withPackages (ps: with ps; [
      httpx
    ]))
  ];

  sops.secrets."mollysocket-env" = {
    owner = "mollysocket";
    mode = "0400";
  };

  
  sops.secrets."mollysocket-vapid" = {
    owner = "mollysocket";
    mode = "0400";
  };

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };

  services.openssh.enable = true;

  services.gotify = {
    enable = true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.gotify-server;
    environment = {
      GOTIFY_SERVER_PORT = 8080;
    };
  };

  services.uptime-kuma = {
    enable = true;
    settings = {
      HOST = "0.0.0.0";
      PORT = "3001";
    };
  };

  services.mollysocket = {
    enable = true;
    settings = { 
      host = "0.0.0.0";
      port = 8020;
      allowed_endpoints = [ "https://drive.montycasa.com" ];
      # allowed_uuids = [ "*" ];
      vapid_key_file = config.sops.secrets.mollysocket-vapid.path;
      environmentFile = config.sops.secrets.mollysocket-env.path;
        # Contains MOLLY_ALLOWED_UUIDS
      # log_level = "info";
    };
  };

  users.users.mollysocket = {
    isNormalUser = true;
    description = "Molly Socket";
  };

  # extra-services.simplex-smp-server = {
  #   enable = true;
  #   environmentFile = config.sops.secrets.simplex-smp-env.path;
  # };

  # nixpkgs.config.allowBroken = true;
  # extra-services.simplexmq-relay = {
  #   enable = true;
  #   host = "smp.montycasa.com";
  # };

  networking.firewall.allowedTCPPorts = [ 8080 3001 ];

  system.stateVersion = "24.05";
}
