{ pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;
  
  services.openssh.enable = true;

  virtualisation.containers.enable = true;

  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      omada-controller = {
        image = "mbentley/omada-controller:6.0.0.25";
        ports = [
          "8088:8088"   # HTTP portal
          "8043:8043"   # HTTPS portal
          "8843:8843"   # HTTPS portal for guest network
          "29810:29810/udp" # EAP discovery
          "29811:29811" # Manager v1
          "29812:29812" # Adopt v1
          "29813:29813" # Upgrade v1
          "29814:29814" # Manager v2
        ];
        volumes = [
          "/var/lib/omada/data:/opt/tplink/EAPController/data"
          "/var/lib/omada/logs:/opt/tplink/EAPController/logs"
        ];
        environment = {
          TZ = "America/New_York"; # Adjust to your timezone
        };
      };
    };
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/omada 0755 root root -"
    "d /var/lib/omada/data 0755 root root -"
    "d /var/lib/omada/logs 0755 root root -"
  ];

  networking.firewall.allowedTCPPorts = [ 8088 8043 8843 29811 29812 29813 29814 ];
  networking.firewall.allowedUDPPorts = [ 29810 ];

  system.stateVersion = "25.11";
}