{ pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    ../../../users/patrick/hosts/nix-fury
    # ../../secrets
  ];
	
  environment.systemPackages = with pkgs; [
		ansible
    ansible-lint
    terraform
    sshpass
    lazygit

    # This is required for the ansibleguy.opnsense ansible role
    (python3.withPackages (ps: with ps; [
      httpx
    ]))
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };

  services.openssh.enable = true;

  services.gotify = {
    enable = true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.gotify-server;
    environment = {
      GOTIFY_SERVER_PORT = 8080;
    };
  };

  # services.uptime-kuma = {
  #   enable = true;
  #   settings = {
  #     HOST = "0.0.0.0";
  #     PORT = "3001";
  #   };
  # };

  networking.firewall.allowedTCPPorts = [ 8080 3001 ];

  system.stateVersion = "24.05";
}
