{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    git
    jq
  ];

  networking.hostName = "openclaw";

  networking.firewall.allowedTCPPorts = [ 8384 22000 ];
  networking.firewall.allowedUDPPorts = [ 22000 21027 ];

  # Create openclaw user
  users.users.openclaw = {
    isNormalUser = true;
    description = "Openclaw service user";
    home = "/home/openclaw";
    createHome = true;
    linger = true;  # Enable user services to run without login
    shell = pkgs.fish;
  };
  programs.fish.enable = true;

  services.openssh.enable = true;

  services.syncthing = {
    enable = true;
    user = "openclaw";
    dataDir = "/var/lib/syncthing";
    guiAddress = "0.0.0.0:8384";
    # overrideDevices = false;  # Don't reset devices on rebuild
    # overrideFolders = false;  # Don't reset folders on rebuild
    settings.gui = {
      user = "patrick";
      password = "$2b$05$HyI3HBR7.6RpSjKnXJVXgOVfq/Kvmc6sDOpnYJ8EbY5U199kmLKZG";
    };
  };

  sops.secrets = {
    openclaw-telegram-token = {
      owner = "openclaw";
    };
    openclaw-env = {
      owner = "openclaw";
      
      # ANTHROPIC_API_KEY
      # OPENCODE_API_KEY
      # HASS_SERVER
      # HASS_TOKEN
    };
  };

  extra-services.mount_notes.enable = true;

  systemd.tmpfiles.rules = [
    "d /var/lib/openclaw 0755 root root -"
    "d /var/lib/syncthing 0755 openclaw openclaw -"
  ];

  home-manager.users.openclaw = { pkgs, lib, ... }: {
    home.stateVersion = "25.11";
    home.packages = with pkgs; [
      # home-assistant-cli
      # rclone
    ];

    programs.home-manager.enable = true;

    # Clean up old backup files before activation to prevent conflicts
    home.activation.cleanupOldBackups = lib.hm.dag.entryBefore ["checkLinkTargets"] ''
      $DRY_RUN_CMD rm -f ~/.openclaw/*.backup
    '';

    programs.openclaw = {
      enable = true;
      documents = ./documents;

      bundledPlugins = {
        summarize.enable = true;   # Summarize web pages, PDFs, videos
        peekaboo.enable = true;    # Take screenshots
        oracle.enable = false;     # Web search
        sag.enable = false;        # Text-to-speech
        camsnap.enable = false;    # Camera snapshots
        # gogcli.enable = false;     # Google Calendar
        # goplaces.enable = true;    # Google Places API
      };

      instances.default = {
        enable = true;
        systemd.enable = true;

        config = {
          gateway = {
            mode = "local";
            auth = {
              token = "local-dev-token";  # For local mode, can be any value
            };
          };

          # Telegram channel configuration
          channels.telegram = {
            enabled = true;
            tokenFile = config.sops.secrets.openclaw-telegram-token.path;
            allowFrom = [ 748642877 ];
            groups = {
              "*" = { requireMention = true; };
            };
          };

          # Enable telegram plugin
          plugins.entries.telegram.enabled = true;
        };

        # Plugins can be added here after initial setup
        # To add plugins, you'll need to add them as flake inputs first
        plugins = [ ];
      };
    };

    # Copy .env file from SOPS secret
    systemd.user.services.openclaw-gateway = {
      Unit = {
        After = [ "network.target" ];
      };
      Service = {
        ExecStartPre = pkgs.writeShellScript "setup-openclaw-env" ''
          ${pkgs.coreutils}/bin/mkdir -p /home/openclaw/.openclaw
          ${pkgs.coreutils}/bin/cp ${config.sops.secrets.openclaw-env.path} /home/openclaw/.openclaw/.env
          ${pkgs.coreutils}/bin/chmod 600 /home/openclaw/.openclaw/.env
        '';
      };
      Install = {
        WantedBy = [ "default.target" ];
      };
    };

  };


  system.stateVersion = "25.11";
}
