{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    git
    jq
  ];

  networking.hostName = "openclaw";

  # Create openclaw user
  users.users.openclaw = {
    isNormalUser = true;
    description = "Openclaw service user";
    home = "/home/openclaw";
    createHome = true;
  };

  services.openssh.enable = true;

  sops.secrets = {
    openclaw-telegram-token = {
      owner = "openclaw";
    };
    openclaw-anthropic-key = {
      owner = "openclaw";
    };
    openclaw-opencode-key = {
      owner = "openclaw";
    };
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/openclaw 0755 root root -"
  ];

  home-manager.users.openclaw = { pkgs, lib, ... }: {
    home.stateVersion = "25.11";
    programs.home-manager.enable = true;

    programs.openclaw = {
      enable = true;
      documents = ./documents;

      bundledPlugins = {
        summarize.enable = true;   # Summarize web pages, PDFs, videos
        peekaboo.enable = true;    # Take screenshots
        oracle.enable = false;     # Web search
        sag.enable = false;        # Text-to-speech
        camsnap.enable = false;    # Camera snapshots
        # gogcli.enable = false;     # Google Calendar
        # goplaces.enable = true;    # Google Places API
      };

      instances.default = {
        enable = true;
        systemd.enable = true;

        config = {
          gateway = {
            mode = "local";
            auth = {
              token = "local-dev-token";  # For local mode, can be any value
            };
          };

          # Telegram channel configuration
          channels.telegram = {
            enabled = true;
            tokenFile = config.sops.secrets.openclaw-telegram-token.path;
            allowFrom = [ 748642877 ];
            groups = {
              "*" = { requireMention = true; };
            };
          };
        };

        # Plugins can be added here after initial setup
        # To add plugins, you'll need to add them as flake inputs first
        plugins = [ ];
      };
    };

    # Load API keys from SOPS secrets into OpenClaw .env file
    systemd.user.services.openclaw-gateway = {
      Service = {
        ExecStartPre = pkgs.writeShellScript "setup-openclaw-env" ''
          ${pkgs.coreutils}/bin/mkdir -p /home/openclaw/.openclaw
          {
            ${pkgs.coreutils}/bin/echo -n "ANTHROPIC_API_KEY="
            ${pkgs.coreutils}/bin/cat ${config.sops.secrets.openclaw-anthropic-key.path}
            ${pkgs.coreutils}/bin/echo -n "OPENCODE_API_KEY="
            ${pkgs.coreutils}/bin/cat ${config.sops.secrets.openclaw-opencode-key.path}
          } > /home/openclaw/.openclaw/.env
          ${pkgs.coreutils}/bin/chmod 600 /home/openclaw/.openclaw/.env
        '';
      };
    };
  };


  system.stateVersion = "25.11";
}
