nrs host="$HOSTNAME":
  sudo nixos-rebuild switch --flake github:pmontgo33/nix-config#{{host}} --refresh

nrs-wtf host="$HOSTNAME":
  sudo nixos-rebuild switch --flake github:pmontgo33/nix-config#{{host}} --refresh --show-trace --print-build-logs --verbose
