{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  sops.secrets.cloudflare-api-token = {
    owner = "caddy";
    mode = "0400";
  };

  extra-services.caddy-proxy = {
    enable = true;
    cloudflareTokenFile = config.sops.secrets.cloudflare-api-token.path;
    
    services = {
      
      "stark.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.93:8006"; 
      };
      
      "starlord.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.95:8006"; 
      };

      "loki.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.97:8006"; 
      };

      # "wakanda.montycasa.net" = { 
      #   protocol = "https"; 
      #   upstream = "100.122.26.79:8006"; 
      # };

      "pbs.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.102:8007"; 
      };

      "truenas.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.99:443"; 
      };

      "uptime.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.106:3001"; 
      };

      "omada.montycasa.net" = { 
        protocol = "https"; 
        upstream = "192.168.86.111:8043"; 
      };

      "router.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.1:80"; 
      };

      "blocker.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.1:3000"; 
      };
      
      "git.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.120:3000"; 
      };

      "qbittorrent.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:8080"; 
      };

      "radarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:7878"; 
      };

      "sonarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:8989"; 
      };

      "bazarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:6767"; 
      };

      "prowlarr.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.114:9696"; 
      };

      "frigate.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.116:5000"; 
      };

      "dockge.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.112:5001"; 
      };

      "homepage.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.118:8082"; 
      };

      "paperless-ngx.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.126:8000"; 
      };

      "myspeed.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.125:5216"; 
      };

      "grist.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.132:8484"; 
      };

      "syncthing.montycasa.net" = { 
        protocol = "http"; 
        upstream = "192.168.86.99:20910"; 
      };
    };

    # layer4SniServices = {
    #   "git.montycasa.net" = { 
    #     protocol = "tcp"; 
    #     upstream = "192.168.86.120:22"; 
    #   };
    # };
  };

  extra-services.tailscale = {
    enable = true;
    userspace-networking = true;
  };
  
  services.openssh.enable = true;  

  system.stateVersion = "25.05";
}