{ pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];
	
  environment.systemPackages = with pkgs; [
    # git
    # gitAndTools.git-lfs
  ];

  services.openssh.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  services.forgejo = {
    enable = true;
    
    settings = {

      # APP_NAME = "Monty Git";

      server = {
        DOMAIN = "git.montycasa.net";
        ROOT_URL = "https://git.montycasa.net/";
        HTTP_PORT = 3000;
        SSH_PORT = 22;
      };
      
      service = {
        DISABLE_REGISTRATION = true;
      };
      
      # Add other settings from old app.ini here
    };
  };

  networking.firewall.allowedTCPPorts = [ 3000 22 ];

  system.stateVersion = "25.05";
}
