{ pkgs, config, modulesPath, inputs, outputs, ... }:

let
  forgejo-mcp = inputs.nixpkgs-unstable.legacyPackages.${pkgs.stdenv.hostPlatform.system}.forgejo-mcp;
in
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    # git
    # gitAndTools.git-lfs
  ];

  services.openssh.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  services.forgejo = {
    enable = true;

    settings = {

      # APP_NAME = "Monty Git";

      server = {
        DOMAIN = "git.montycasa.net";
        ROOT_URL = "https://git.montycasa.net/";
        HTTP_PORT = 3000;
        SSH_PORT = 22;
      };

      service = {
        DISABLE_REGISTRATION = true;
      };

      # Add other settings from old app.ini here
    };
  };

  # forgejo-mcp: MCP server for AI tools to interact with Forgejo
  sops.secrets."forgejo-mcp-env" = {
    mode = "0400";
    restartUnits = [ "forgejo-mcp.service" ];
  };

  systemd.services.forgejo-mcp = {
    description = "Forgejo MCP Server (SSE)";
    after = [ "network.target" "forgejo.service" ];
    wants = [ "forgejo.service" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "simple";
      DynamicUser = true;
      EnvironmentFile = config.sops.secrets."forgejo-mcp-env".path;
      ExecStart = "${forgejo-mcp}/bin/forgejo-mcp --transport sse --url https://git.montycasa.net --sse-port 8080";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  networking.firewall.allowedTCPPorts = [ 3000 22 8080 ];

  system.stateVersion = "25.05";
}
