{ pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];
	
  environment.systemPackages = with pkgs; [
    git
    gitAndTools.git-lfs
  ];

  services.openssh.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };

  services.forgejo = {
    enable = true;
    
    # Database configuration
    database = {
      type = "postgres";
    };
    
    settings = {
      server = {
        DOMAIN = "git.montycasa.net";
        ROOT_URL = "https://git.montycasa.net/";
        HTTP_PORT = 3000;
        SSH_PORT = 22;
      };
      
      service = {
        DISABLE_REGISTRATION = true;  # Set according to your needs
      };
      
      # Add other settings from your old app.ini here
    };
  };

  services.postgresql = {
    enable = true;
    ensureDatabases = [ "forgejo" ];
    ensureUsers = [{
      name = "forgejo";
      ensureDBOwnership = true;
    }];
  };

  networking.firewall.allowedTCPPorts = [ 3000 22 ];

  system.stateVersion = "25.05";
}
