{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;
  extra-services.mount_media = {
    enable = true;
    readOnly = true;
  };

  sops = {
    secrets = {
      
    };
  };

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Enable virtualisation for containers
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /var/lib/audiobookshelf/config 0755 root root -"
    "d /var/lib/audiobookshelf/metadata 0755 root root -"
  ];

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      audiobookshelf = {
        image = "ghcr.io/advplyr/audiobookshelf:latest";
        ports = [ "13378:80" ];
        volumes = [
          "/var/lib/audiobookshelf/config:/config"
          "/var/lib/audiobookshelf/metadata:/metadata"
          "/mnt/media/audiobooks:/audiobooks"
        ];
        environment = {
          TZ = "America/New_York";
        };
        extraOptions = [
          "--pull=newer"
        ];
      };
    };
  };

  networking.firewall.allowedTCPPorts = [ 13378 ];

  system.stateVersion = "25.11";
}