{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    git
    jq
    signal-cli
    qrencode
  ];

  networking.hostName = "moltbot";

  # Create moltbot user
  users.users.moltbot = {
    isNormalUser = true;
    description = "Moltbot service user";
    home = "/home/moltbot";
    createHome = true;
  };

  services.openssh.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  sops.secrets = {
    moltbot-anthropic-key = {
      owner = "moltbot";
    };
    moltbot-env = {
      owner = "moltbot";
    };
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/moltbot 0755 root root -"
  ];

  home-manager.users.moltbot = { pkgs, lib, ... }: {
    home.stateVersion = "25.11";
    programs.home-manager.enable = true;

    # Add coreutils for the wrapper script to use cat command
    home.packages = [ pkgs.coreutils ];

    # Override systemd service to inject Signal phone numbers from secrets
    systemd.user.services.moltbot-gateway.Service = {
      Type = "simple";  # Tell systemd this is a long-running service
      EnvironmentFile = "/run/secrets/moltbot-env";
      Environment = "PATH=${pkgs.coreutils}/bin:/run/current-system/sw/bin";
        ExecStartPre = pkgs.writeShellScript "inject-signal-config" ''
          # Source environment file to get Signal phone number
          . /run/secrets/moltbot-env

          # Paths to consider (manifest + filtered copies)
          for target in /home/moltbot/.moltbot/moltbot.json /home/moltbot/.moltbot/moltbot-filtered.json; do
            if [ -f "$target" ]; then
              ${pkgs.jq}/bin/jq \
                --arg account "$SIGNAL_ACCOUNT_PHONE" \
                --arg allowFrom "$SIGNAL_ALLOWED_PHONE" \
                'del(.messages.queue.byProvider) |
                 .channels.signal = {
                   "enabled": true,
                   "cliPath": "signal-cli",
                   "account": $account,
                   "dmPolicy": "allowlist",
                   "allowFrom": [$allowFrom]
                 } |
                 .plugins = (.plugins // {}) |
                 .plugins.slots = (.plugins.slots // {}) |
                 .plugins.slots.memory = "none"
                ' "$target" > "$target".tmp && \
              mv "$target".tmp "$target"
            fi
          done

          # Remove the filtered cache so the gateway sees the current config only
          rm -f /home/moltbot/.moltbot/moltbot-filtered.json
        '';

    };

    programs.moltbot = {
      documents = ./documents;

      firstParty = {
          summarize.enable = true;   # Summarize web pages, PDFs, videos
          peekaboo.enable = true;    # Take screenshots
          oracle.enable = false;     # Web search
          sag.enable = false;        # Text-to-speech
          gogcli.enable = false;     # Google Calendar
        };

      instances.default = {
        enable = true;

        systemd.enable = true;

        providers.anthropic = {
          apiKeyFile = config.sops.secrets.moltbot-anthropic-key.path;
        };

        # Use the proper config field (not configOverrides)
        config = {
          # Signal channel configuration (phone numbers injected via ExecStartPre)
          channels.signal = {
            enabled = true;
            cliPath = "signal-cli";
            dmPolicy = "allowlist";
          };
          # Disable memory plugin (not available in nix-moltbot)
          plugins.slots.memory = "none";
        };

        plugins = [
          # Example plugin without config:
          # { source = "github:acme/hello-world"; }
        ];
      };
    };
  };


  system.stateVersion = "25.11";
}
