{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    git
  ];

  networking.hostName = "moltbot";

  services.openssh.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  sops.secrets = {
    moltbot-anthropic-key = {};
    moltbot-discord-token = {};
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/moltbot 0755 root root -"
  ];

  home-manager.users.root = { pkgs, ... }: {
    home.stateVersion = "25.11";
    programs.home-manager.enable = true;

    programs.moltbot = {
      documents = ./documents;

      firstParty = {
          summarize.enable = true;   # Summarize web pages, PDFs, videos
          peekaboo.enable = true;    # Take screenshots
          oracle.enable = false;     # Web search
          sag.enable = false;        # Text-to-speech
          gogcli.enable = false;     # Google Calendar
        };

      instances.default = {
        enable = true;

        systemd.enable = true;

        providers.anthropic = {
          apiKeyFile = config.sops.secrets.moltbot-anthropic-key.path;
        };

        config.channels.discord = {
          enabled = true;
          token = builtins.readFile config.sops.secrets.moltbot-discord-token.path;
          dm = {
            policy = "allowlist";  # Options: "open", "allowlist", "disabled"
            allowFrom = [351909064172634112];  # Add Discord user IDs here
          };
          guilds = {
            policy = "disabled";  # Options: "open", "allowlist", "disabled" (you wanted DMs only)
          };
        };

        plugins = [
          # Example plugin without config:
          # { source = "github:acme/hello-world"; }
        ];
      };
    };
  };


  system.stateVersion = "25.11";
}
