{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    git
  ];

  networking.hostName = "moltbot";

  # Create moltbot user
  users.users.moltbot = {
    isNormalUser = true;
    description = "Moltbot service user";
    home = "/home/moltbot";
    createHome = true;
  };

  services.openssh.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  sops.secrets = {
    moltbot-anthropic-key = {
      owner = "moltbot";
    };
    moltbot-discord-token = {
      owner = "moltbot";
    };
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/moltbot 0755 root root -"
  ];

  home-manager.users.moltbot = { pkgs, ... }: {
    home.stateVersion = "25.11";
    programs.home-manager.enable = true;

    # Override systemd service to add Discord token environment file
    systemd.user.services.moltbot-gateway = {
      Service = {
        EnvironmentFile = config.sops.secrets.moltbot-discord-token.path;
      };
    };

    programs.moltbot = {
      documents = ./documents;

      firstParty = {
          summarize.enable = true;   # Summarize web pages, PDFs, videos
          peekaboo.enable = true;    # Take screenshots
          oracle.enable = false;     # Web search
          sag.enable = false;        # Text-to-speech
          gogcli.enable = false;     # Google Calendar
        };

      instances.default = {
        enable = true;

        systemd.enable = true;

        providers.anthropic = {
          apiKeyFile = config.sops.secrets.moltbot-anthropic-key.path;
        };

        configOverrides = {
          channels.discord = {
            enabled = true;
            # Token will be provided via DISCORD_BOT_TOKEN environment variable
            dm = {
              policy = "allowlist";  # Options: "open", "allowlist", "disabled"
              allowFrom = [351909064172634112];  # Add Discord user IDs here
            };
            # guilds is an object of guild IDs, empty = no guild support
            guilds = {};
          };
          # Fix routing config - should be byChannel not byProvider
          messages.queue = {
            mode = "interrupt";
            byChannel = {
              discord = "queue";
            };
          };
        };

        plugins = [
          # Example plugin without config:
          # { source = "github:acme/hello-world"; }
        ];
      };
    };
  };


  system.stateVersion = "25.11";
}
