{ config, pkgs, modulesPath, inputs, outputs, ... }:

let
  dataDir = "/var/lib/erpnext";
in
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;

  sops.secrets.erpnext-mysql-root-password = {};
  sops.secrets.erpnext-mysql-password = {};

  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  networking.firewall.allowedTCPPorts = [ 80 443 8000 ];

  systemd.tmpfiles.rules = [
    "d ${dataDir} 0755 root root -"
    "d ${dataDir}/mariadb 0755 root root -"
    "d ${dataDir}/redis-cache 0755 root root -"
    "d ${dataDir}/redis-queue 0755 root root -"
    "d ${dataDir}/sites 0755 root root -"
  ];

  systemd.services.podman-erpnext-network = {
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.podman}/bin/podman network create erpnext-network || true";
      ExecStop = "${pkgs.podman}/bin/podman network rm erpnext-network || true";
    };
  };

  virtualisation.oci-containers = {
    backend = "podman";
    
    containers = {
      erpnext-mariadb = {
        image = "mariadb:10.6";
        autoStart = true;
        volumes = [
          "${dataDir}/mariadb:/var/lib/mysql"
        ];
        environmentFiles = [
          config.sops.secrets.erpnext-mysql-root-password.path
          config.sops.secrets.erpnext-mysql-password.path
        ];
        environment = {
          MYSQL_DATABASE = "erpnext";
          MYSQL_USER = "erpnext";
        };
        extraOptions = [
          "--network=erpnext-network"
          "--health-cmd=healthcheck.sh --connect --innodb_initialized"
          "--health-interval=1s"
          "--health-timeout=5s"
          "--health-retries=30"
        ];
        cmd = [
          "--character-set-server=utf8mb4"
          "--collation-server=utf8mb4_unicode_ci"
          "--skip-character-set-client-handshake"
          "--skip-innodb-read-only-compressed"
        ];
      };

      erpnext-redis-cache = {
        image = "redis:alpine";
        autoStart = true;
        volumes = [
          "${dataDir}/redis-cache:/data"
        ];
        extraOptions = [
          "--network=erpnext-network"
        ];
      };

      erpnext-redis-queue = {
        image = "redis:alpine";
        autoStart = true;
        volumes = [
          "${dataDir}/redis-queue:/data"
        ];
        extraOptions = [
          "--network=erpnext-network"
        ];
      };

      erpnext-backend = {
        image = "frappe/erpnext:v15.24.0";
        autoStart = true;
        dependsOn = [
          "erpnext-mariadb"
          "erpnext-redis-cache"
          "erpnext-redis-queue"
        ];
        volumes = [
          "${dataDir}/sites:/home/frappe/frappe-bench/sites"
        ];
        environment = {
          MARIADB_HOST = "erpnext-mariadb";
          REDIS_CACHE = "redis://erpnext-redis-cache:6379";
          REDIS_QUEUE = "redis://erpnext-redis-queue:6379";
          FRAPPE_SITE_NAME_HEADER = "erpnext.local";
        };
        extraOptions = [
          "--network=erpnext-network"
        ];
      };

      erpnext-frontend = {
        image = "frappe/erpnext:v15.24.0";
        autoStart = true;
        dependsOn = [
          "erpnext-backend"
        ];
        ports = [
          "8000:8080"
        ];
        volumes = [
          "${dataDir}/sites:/home/frappe/frappe-bench/sites"
        ];
        environment = {
          BACKEND = "erpnext-backend:8000";
          FRAPPE_SITE_NAME_HEADER = "erpnext.local";
          SOCKETIO_PORT = "9000";
        };
        extraOptions = [
          "--network=erpnext-network"
        ];
        cmd = [ "nginx-entrypoint.sh" ];
      };

      erpnext-queue-short = {
        image = "frappe/erpnext:v15.24.0";
        autoStart = true;
        dependsOn = [
          "erpnext-backend"
        ];
        volumes = [
          "${dataDir}/sites:/home/frappe/frappe-bench/sites"
        ];
        environment = {
          MARIADB_HOST = "erpnext-mariadb";
          REDIS_CACHE = "redis://erpnext-redis-cache:6379";
          REDIS_QUEUE = "redis://erpnext-redis-queue:6379";
        };
        extraOptions = [
          "--network=erpnext-network"
        ];
        cmd = [ "bench" "worker" "--queue" "short" ];
      };

      erpnext-queue-long = {
        image = "frappe/erpnext:v15.24.0";
        autoStart = true;
        dependsOn = [
          "erpnext-backend"
        ];
        volumes = [
          "${dataDir}/sites:/home/frappe/frappe-bench/sites"
        ];
        environment = {
          MARIADB_HOST = "erpnext-mariadb";
          REDIS_CACHE = "redis://erpnext-redis-cache:6379";
          REDIS_QUEUE = "redis://erpnext-redis-queue:6379";
        };
        extraOptions = [
          "--network=erpnext-network"
        ];
        cmd = [ "bench" "worker" "--queue" "long" ];
      };

      erpnext-scheduler = {
        image = "frappe/erpnext:v15.24.0";
        autoStart = true;
        dependsOn = [
          "erpnext-backend"
        ];
        volumes = [
          "${dataDir}/sites:/home/frappe/frappe-bench/sites"
        ];
        environment = {
          MARIADB_HOST = "erpnext-mariadb";
          REDIS_CACHE = "redis://erpnext-redis-cache:6379";
          REDIS_QUEUE = "redis://erpnext-redis-queue:6379";
        };
        extraOptions = [
          "--network=erpnext-network"
        ];
        cmd = [ "bench" "schedule" ];
      };
    };
  };

  environment.systemPackages = with pkgs; [
    (writeScriptBin "erpnext-init-site" ''
      #!/usr/bin/env bash
      set -e
      
      SITE_NAME=''${1:-erpnext.local}
      ADMIN_PASSWORD=''${2:-admin123}
      
      # Read root password from sops secret
      MYSQL_ROOT_PASSWORD=$(cat ${config.sops.secrets."erpnext/mysql_root_password".path})
      
      echo "Initializing ERPNext site: $SITE_NAME"
      echo "Waiting for MariaDB to be ready..."
      sleep 10
      
      ${pkgs.podman}/bin/podman exec erpnext-backend \
        bench new-site "$SITE_NAME" \
        --db-root-password "$MYSQL_ROOT_PASSWORD" \
        --admin-password "$ADMIN_PASSWORD" \
        --install-app erpnext \
        --set-default
      
      echo "Site initialized successfully!"
      echo "Access ERPNext at: http://localhost:8000"
      echo "Username: Administrator"
      echo "Password: $ADMIN_PASSWORD"
    '')
    
    (writeScriptBin "erpnext-backup" ''
      #!/usr/bin/env bash
      SITE_NAME=''${1:-erpnext.local}
      ${pkgs.podman}/bin/podman exec erpnext-backend \
        bench --site "$SITE_NAME" backup
      
      echo "Backup completed. Files stored in ${dataDir}/sites/$SITE_NAME/private/backups/"
    '')
  ];
  

  system.stateVersion = "25.05";
}