{ config, pkgs, modulesPath, inputs, outputs, ... }:

{

  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    ../../secrets
  ];

  extra-services.tailscale.enable = true;

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;
	
  # Enable virtualisation for containers
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /var/lib/endurain 0755 root root -"
    "d /var/lib/endurain/postgresql 0755 70 70 -"
    "d /var/lib/endurain/uploads 0755 root root -"
  ];

  # sops secrets configuration
  sops.secrets = {
    endurain-db-password = {
      sopsFile = ../../secrets/secrets.yaml;
      owner = "root";
      group = "root";
      mode = "0400";
    };
    endurain-secret-key = {
      sopsFile = ../../secrets/secrets.yaml;
      owner = "root";
      group = "root";
      mode = "0400";
    };
  };

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      endurain-db = {
        image = "postgres:16-alpine";
        autoStart = true;
        environment = {
          POSTGRES_DB = "endurain";
          POSTGRES_USER = "endurain";
        };
        environmentFiles = [
          config.sops.secrets.endurain-db-password.path
        ];
        volumes = [
          "/var/lib/endurain/postgresql:/var/lib/postgresql/data"
        ];
        extraOptions = [
          "--network=endurain-net"
          "--health-cmd=pg_isready -U endurain"
          "--health-interval=10s"
          "--health-timeout=5s"
          "--health-retries=5"
        ];
      };

      endurain-api = {
        image = "joaovitoriasilva/endurain:latest";
        autoStart = true;
        dependsOn = [ "endurain-db" ];
        ports = [
          "8000:8000"
        ];
        environment = {
          DATABASE_HOST = "endurain-db";
          DATABASE_PORT = "5432";
          DATABASE_NAME = "endurain";
          DATABASE_USER = "endurain";
          REDIS_HOST = "endurain-redis";
          REDIS_PORT = "6379";
        };
        environmentFiles = [
          config.sops.secrets.endurain-db-password.path
          config.sops.secrets.endurain-secret-key.path
        ];
        volumes = [
          "/var/lib/endurain/uploads:/app/uploads"
        ];
        extraOptions = [
          "--network=endurain-net"
          "--health-cmd=curl -f http://localhost:8000/health || exit 1"
          "--health-interval=30s"
          "--health-timeout=10s"
          "--health-retries=3"
        ];
      };

      endurain-redis = {
        image = "redis:7-alpine";
        autoStart = true;
        extraOptions = [
          "--network=endurain-net"
          "--health-cmd=redis-cli ping"
          "--health-interval=10s"
          "--health-timeout=5s"
          "--health-retries=5"
        ];
      };
    };
  };

  systemd.services.init-endurain-network = {
    description = "Create the network for Endurain";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.bash}/bin/bash -c '${pkgs.podman}/bin/podman network inspect endurain-net >/dev/null 2>&1 || ${pkgs.podman}/bin/podman network create endurain-net'";
    };
  };

  systemd.services.podman-endurain-db.after = [ "init-endurain-network.service" ];
  systemd.services.podman-endurain-api.after = [ "init-endurain-network.service" ];
  systemd.services.podman-endurain-redis.after = [ "init-endurain-network.service" ];

  networking.firewall.allowedTCPPorts = [ 8000 ];
  
  system.stateVersion = "25.05";
}