{ config, pkgs, modulesPath, inputs, outputs, ... }:

let
  # Create a proper environment file for PostgreSQL
  endurain-db-env = pkgs.writeText "endurain-db.env" ''
    POSTGRES_PASSWORD_FILE=${config.sops.secrets.endurain-db-password.path}
  '';
in
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    ../../secrets
  ];

  extra-services.tailscale.enable = true;

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Enable virtualisation for containers
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /var/lib/endurain 0755 root root -"
    "d /var/lib/endurain/postgresql 0755 70 70 -"
    "d /var/lib/endurain/uploads 0755 root root -"
    "d /var/lib/endurain/strava_tmp 0755 root root -"
  ];

  # sops secrets configuration
  sops.secrets = {
    endurain-db-password = {
      sopsFile = ../../secrets/secrets.yaml;
      owner = "root";
      group = "root";
      mode = "0400";
    };
    endurain-first-user-email = {
      sopsFile = ../../secrets/secrets.yaml;
      owner = "root";
      group = "root";
      mode = "0400";
    };
    endurain-first-user-password = {
      sopsFile = ../../secrets/secrets.yaml;
      owner = "root";
      group = "root";
      mode = "0400";
    };
  };

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      endurain-db = {
        image = "docker.io/library/postgres:16-alpine";
        autoStart = true;
        environment = {
          POSTGRES_DB = "endurain";
          POSTGRES_USER = "endurain";
          POSTGRES_PASSWORD_FILE = "/run/secrets/db-password";
          PGDATA = "/var/lib/postgresql/data/pgdata";
        };
        volumes = [
          "/var/lib/endurain/postgresql:/var/lib/postgresql/data"
          "${config.sops.secrets.endurain-db-password.path}:/run/secrets/db-password:ro"
        ];
        extraOptions = [
          "--network=endurain-net"
          "--health-cmd=pg_isready -U endurain"
          "--health-interval=10s"
          "--health-timeout=5s"
          "--health-retries=5"
        ];
      };
      
      endurain = {
        image = "ghcr.io/joaovitoriasilva/endurain:latest";
        autoStart = true;
        dependsOn = [ "endurain-db" ];
        ports = [
          "8080:8080"
        ];
        environment = {
          TZ = "America/New_York";
          # Database settings
          ENDURAIN_DATABASE_HOST = "endurain-db";
          ENDURAIN_DATABASE_PORT = "5432";
          ENDURAIN_DATABASE_NAME = "endurain";
          ENDURAIN_DATABASE_USER = "endurain";
          # UID/GID
          UID = "1000";
          GID = "1000";
        };
        environmentFiles = [
          config.sops.secrets.endurain-db-password.path
          config.sops.secrets.endurain-first-user-email.path
          config.sops.secrets.endurain-first-user-password.path
          # Optional: Add Strava secrets
          # config.sops.secrets.endurain-strava-client-id.path
          # config.sops.secrets.endurain-strava-client-secret.path
        ];
        volumes = [
          "/var/lib/endurain/uploads:/app/uploads"
          "/var/lib/endurain/strava_tmp:/app/strava_tmp"
        ];
        extraOptions = [
          "--network=endurain-net"
          "--health-cmd=curl -f http://localhost:8080/api/health || exit 1"
          "--health-interval=30s"
          "--health-timeout=10s"
          "--health-retries=3"
        ];
      };
    };
  };

  systemd.services.init-endurain-network = {
    description = "Create the network for Endurain";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.bash}/bin/bash -c '${pkgs.podman}/bin/podman network inspect endurain-net >/dev/null 2>&1 || ${pkgs.podman}/bin/podman network create endurain-net'";
    };
  };

  systemd.services.podman-endurain-db.after = [ "init-endurain-network.service" ];
  systemd.services.podman-endurain.after = [ "init-endurain-network.service" ];

  networking.firewall.allowedTCPPorts = [ 8080 ];

  system.stateVersion = "25.05";
}