{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  extra-services.tailscale = {
    enable = true;
    userspace-networking = true;
  };

  # sops secrets configuration
  sops.secrets."immich-secrets" = {
    # sopsFile = ../../secrets/secrets.yaml;
    owner = "immich";
    group = "immich";
    mode = "0400";
  };

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  extra-services.mount_home_media.enable = true;

  # # Create necessary directories
  systemd.tmpfiles.rules = [
    "d /mnt/home_media 0755 root root -"
    "Z /mnt/home_media/immich 0750 immich immich -"
  ];

  # Immich service configuration
  services.immich = {
    enable = true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.immich;
    # host = "0.0.0.0";
    # port = 2283;
    openFirewall = true;
    mediaLocation = "/mnt/home_media/immich";
    accelerationDevices = null;
    # secretsFile = config.sops.secrets."immich-secrets".path;
    environment = {
      TZ = "America/New_York";
    };
    settings = {
      #server.externalDomain = "";
      newVersionCheck.enabled = true;
    };

    database = {
      enable = true;
      createDB = true;
    };
  };

  # Add immich user to video and render groups for hardware acceleration
  users.users.immich.extraGroups = [ "video" "render" ];

  # Enable hardware acceleration support
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
    ];
  };

  # networking.firewall.allowedTCPPorts = [ 2283 ];

  system.stateVersion = "25.05";
}