{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  # sops.secrets."caddy-acme-email" = {
  #   owner = "caddy";
  #   mode = "0400";
  # };
  sops.secrets.cloudflare-api-token = {
    owner = "caddy";
    mode = "0400";
  };

  extra-services.caddy-proxy = {
    enable = true;
    cloudflareTokenFile = config.sops.secrets.cloudflare-api-token.path;
    
    services = {
      "git.montybeta.org" = { 
        protocol = "http"; 
        upstream = "192.168.86.120:3000"; 
      };
      # "service2.example.com" = { 
      #   protocol = "http"; 
      #   upstream = "192.168.1.10:3001"; 
      # };
    };

    layer4SniServices = {
      "git.montybeta.org" = { 
        protocol = "tcp"; 
        upstream = "192.168.86.120:22"; 
      };
    };
  };

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;  

  system.stateVersion = "25.05";
}