{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  sops = {
      secrets = {
        "onlyoffice-jwt-secret" = {
          owner = "onlyoffice";
          group = "onlyoffice";
          mode = "0400";
        };
      };
    };

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;

  services.gotify.enable = true;

  networking.firewall.allowedTCPPorts = [ 80 ];
  

  system.stateVersion = "25.05";
}