{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  services.openssh.enable = true;

  sops = {
    # defaultSopsFile = ../../secrets/secrets.yaml;
    secrets = {
      "mealie-env" = {};
    };
  };

  services.mealie = {
    enable = true;
    port = 9000;
    listenAddress = "0.0.0.0";

    # Enable local PostgreSQL database
    database.createLocally = true;

    settings = {
      BASE_URL = "https://mealie.montycasa.com";

      # OIDC Configuration for Pocket ID
      OIDC_AUTH_ENABLED = true;
      OIDC_SIGNUP_ENABLED = true;
      OIDC_CONFIGURATION_URL = "https://auth.montycasa.com/.well-known/openid-configuration";
      OAUTH_PROVIDER_NAME = "Pocket ID";
    };

    # Credentials file for sensitive values (OIDC_CLIENT_ID, OIDC_CLIENT_SECRET)
    credentialsFile = config.sops.secrets."mealie-env".path;
  };

  networking.firewall.allowedTCPPorts = [ 9000 ];

  system.stateVersion = "25.11";
}