{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  services.openssh.enable = true;

  services.mealie = {
    enable = true;
    port = 9000;
    listenAddress = "0.0.0.0";

    database.createLocally = true;

    settings = {
      BASE_URL = "https://mealie.montycasa.com";
    };
  };

  networking.firewall.allowedTCPPorts = [ 9000 ];

  system.stateVersion = "25.11";
}