# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e48f748a-21b8-4a29-a195-17da875ffdb6";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/9fe998e9-eb36-496d-85e3-4a7067410706";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e48f748a-21b8-4a29-a195-17da875ffdb6";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/e48f748a-21b8-4a29-a195-17da875ffdb6";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/mnt/home_media" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/e48f748a-21b8-4a29-a195-17da875ffdb6";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e48f748a-21b8-4a29-a195-17da875ffdb6";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/home/patrick/mnt/media" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/home/patrick/mnt/nextcloud" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8128-B110";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
