{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [

  ];

  networking.hostName = "frigate";

  services.openssh.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  systemd.tmpfiles.rules = [
    "d /mnt/media 0755 root root -"
    "d /var/lib/frigate/cache 0755 frigate frigate -"
  ];

  extra-services.mount_media.enable = true;

  # Configure SOPS secrets for Frigate
  sops.secrets.frigate-env = {};

  # Frigate NVR Configuration
  services.frigate = {
    enable = true;
    hostname = "frigate.local";

    # Disable config check since we use runtime env vars for secrets
    checkConfig = false;

    # Enable Intel QuickSync hardware acceleration
    vaapiDriver = "iHD";

    settings = {
      # MQTT Configuration for Home Assistant integration
      mqtt = {
        enabled = true;
        host = "192.168.86.100";
        port = 1883;
        user = "homeassistant";
        password = "{FRIGATE_MQTT_PASSWORD}";
      };

      # Database configuration
      database = {
        path = "/var/lib/frigate/frigate.db";
      };

      # Authentication
      auth = {
        enabled = true;
      };

      # Detector configuration - Using CPU temporarily
      # TODO: Re-enable OpenVINO GPU detection once model path is configured
      detectors = {
        cpu = {
          type = "cpu";
        };
      };

      # FFmpeg hardware acceleration using VAAPI (Intel QuickSync)
      ffmpeg = {
        hwaccel_args = "preset-vaapi";
      };

      # Go2RTC configuration for WebRTC streams
      go2rtc = {
        streams = {
          front_door = [
            "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.54:554/cam/realmonitor?channel=1&subtype=0"
            "ffmpeg:front_door#audio=opus"
          ];
          back_door = [
            "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.53:554/cam/realmonitor?channel=1&subtype=0"
            "ffmpeg:back_door_door#audio=opus"
          ];
          bella_room = [
            "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.51:554/cam/realmonitor?channel=1&subtype=0"
            "ffmpeg:ali_room#audio=opus"
          ];
          girls_room = [
            "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.50/:554/cam/realmonitor?channel=1&subtype=0"
            "ffmpeg:emma_room#audio=opus"
          ];
          nursery = [
            "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.52:554/cam/realmonitor?channel=1&subtype=0"
            "ffmpeg:nursery#audio=opus"
          ];
        };
        webrtc = {
          candidates = [
            "192.168.86.116:8555"
            "stun:8555"
          ];
        };
      };

      # Global recording configuration
      record = {
        enabled = true;
        retain = {
          days = 0;
        };
        alerts = {
          retain = {
            days = 10;
          };
        };
        detections = {
          retain = {
            days = 10;
          };
        };
      };

      # Snapshots configuration
      snapshots = {
        enabled = true;
        retain = {
          default = 10;
        };
      };

      # Timestamp styling
      timestamp_style = {
        position = "tr";
      };

      # Global detection settings
      detect = {
        enabled = true;
      };

      # Additional features
      semantic_search = {
        enabled = false;
        model_size = "small";
      };

      face_recognition = {
        enabled = false;  # Disabled temporarily - causing segfault
        model_size = "small";
      };

      lpr = {
        enabled = false;  # Disabled temporarily - causing segfault
      };

      classification = {
        bird = {
          enabled = true;
        };
      };

      # Camera configurations
      cameras = {
        front_door = {
          ffmpeg = {
            output_args = {
              record = "preset-record-generic-audio-copy";
            };
            inputs = [
              {
                path = "rtsp://127.0.0.1:8554/front_door";
                input_args = "preset-rtsp-restream";
                roles = ["record"];
              }
              {
                path = "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.54:554/cam/realmonitor?channel=1&subtype=1";
                roles = ["detect"];
              }
            ];
          };
          record = {
            enabled = true;
            retain = {
              days = 3;
            };
            alerts = {
              retain = {
                days = 10;
              };
            };
            detections = {
              retain = {
                days = 10;
              };
            };
          };
          detect = {
            enabled = true;
          };
          objects = {
            track = ["person"];
          };
          zones = {
            Front_Porch = {
              coordinates = "0.723,0.24,0.436,0.736,0.321,0.998,0.996,0.99,0.987,0.016,0.712,0.003";
              loitering_time = 0;
            };
            Front_Lawn = {
              coordinates = "0.721,0.197,0.475,0.199,0.331,0.297,0.137,0.477,0.075,0.546,0.084,0.999,0.319,0.998,0.721,0.241";
              loitering_time = 0;
            };
          };
        };

        back_door = {
          ffmpeg = {
            output_args = {
              record = "preset-record-generic-audio-copy";
            };
            inputs = [
              {
                path = "rtsp://127.0.0.1:8554/back_door";
                input_args = "preset-rtsp-restream";
                roles = ["record"];
              }
              {
                path = "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.53:554/cam/realmonitor?channel=1&subtype=1";
                roles = ["detect"];
              }
            ];
          };
          record = {
            enabled = true;
            retain = {
              days = 3;
            };
            alerts = {
              retain = {
                days = 10;
              };
            };
            detections = {
              retain = {
                days = 10;
              };
            };
          };
          detect = {
            enabled = true;
          };
          objects = {
            track = ["person" "dog"];
            filters = {
              person = {
                mask = "0.573,0.17,0.571,0.362,0.619,0.366,0.618,0.17";
              };
            };
          };
          zones = {
            Back_Stoop = {
              coordinates = "0.001,0.702,0,0,0.186,0,0.198,0.646,0.361,0.92,0.326,0.998,0.179,0.997,0.072,0.779";
              loitering_time = 0;
            };
          };
        };

        bella_room = {
          ffmpeg = {
            output_args = {
              record = "preset-record-generic-audio-copy";
            };
            inputs = [
              {
                path = "rtsp://127.0.0.1:8554/bella_room";
                input_args = "preset-rtsp-restream";
                roles = ["record"];
              }
              {
                path = "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.51:554/cam/realmonitor?channel=1&subtype=1";
                roles = ["detect"];
              }
            ];
          };
          record = {
            enabled = true;
            retain = {
              days = 0.125;
            };
          };
          detect = {
            enabled = false;
          };
        };

        girls_room = {
          ffmpeg = {
            output_args = {
              record = "preset-record-generic-audio-copy";
            };
            inputs = [
              {
                path = "rtsp://127.0.0.1:8554/girls_room";
                input_args = "preset-rtsp-restream";
                roles = ["record"];
              }
              {
                path = "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.50:554/cam/realmonitor?channel=1&subtype=1";
                roles = ["detect"];
              }
            ];
          };
          record = {
            enabled = true;
            retain = {
              days = 0.125;
            };
          };
          detect = {
            enabled = false;
          };
        };

        nursery = {
          ffmpeg = {
            output_args = {
              record = "preset-record-generic-audio-copy";
            };
            inputs = [
              {
                path = "rtsp://127.0.0.1:8554/nursery";
                input_args = "preset-rtsp-restream";
                roles = ["record"];
              }
              {
                path = "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@192.168.10.52:554/cam/realmonitor?channel=1&subtype=1";
                roles = ["detect"];
              }
            ];
          };
          record = {
            enabled = true;
            retain = {
              days = 0.25;
            };
          };
          detect = {
            enabled = false;
          };
        };
      };
    };
  };

  # GPU access for LXC - match host device GIDs
  users.groups.renderaccess = {
    gid = 104;  # Match host render device GID
    members = [ "frigate" ];
  };
  users.groups.videoaccess = {
    gid = 44;   # Match host video device GID
    members = [ "frigate" ];
  };

  # Enable hardware graphics support
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver             # VAAPI driver for newer Intel (iHD)
      intel-vaapi-driver             # Legacy VAAPI driver
      libva-vdpau-driver
      vpl-gpu-rt                     # Video Processing Library
    ];
  };

  # Configure Intel GPU hardware acceleration and load secrets
  systemd.services.frigate = {
    serviceConfig = {
      SupplementaryGroups = ["render" "video"];
      AmbientCapabilities = "CAP_PERFMON";
      # Load secrets from SOPS
      EnvironmentFile = config.sops.secrets.frigate-env.path;
    };
    environment = {
      LIBVA_DRIVER_NAME = "iHD";
    };
  };

  # Mount tmpfs for cache (reduces SSD wear)
  fileSystems."/var/lib/frigate/cache" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "size=1G" "mode=0755" ];
  };

  # Open firewall ports for Frigate
  networking.firewall.allowedTCPPorts = [
    5000   # Web UI
    8554   # RTSP feeds
    8555   # WebRTC TCP
    1984   # Go2RTC
    8971   # Additional port from docker-compose
  ];
  networking.firewall.allowedUDPPorts = [
    8555   # WebRTC UDP
  ];

  system.stateVersion = "25.05";
}
