{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    userspace-networking = true;
  };
  
  services.openssh.enable = true;

  systemd.tmpfiles.rules = [
    "d /var/lib/gluetun/tmp 0755 root root -"
    "d /var/lib/qbittorrent 0755 root root -"
    "d /var/lib/transmission_novpn 0755 root root -"
    "d /var/lib/transmission_novpn/config 0755 root root -"
    "d /var/lib/prowlarr/config 0755 root root -"
    "d /var/lib/jackett/config 0755 root root -"
    "d /var/lib/jackett/blackhole 0755 root root -"
    "d /var/lib/sonarr/config 0755 root root -"
    "d /var/lib/radarr/config 0755 root root -"
    "d /var/lib/bazarr/config 0755 root root -"
    "d /var/lib/pinchflat 0755 root root -"
    "d /var/lib/huntarr 0755 root root -"
    "d /mnt/media 0755 root root -"
    "d /mnt/media/downloads 0755 root root -"
    "d /mnt/media/web 0755 root root -"
  ];

  extra-services.mount_media.enable = true;

  sops.secrets.gluetun-env = {};
  sops.secrets.unpackerr-env = {};

  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  systemd.services.init-media-network = {
    description = "Create podman network for media services";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig.Type = "oneshot";
    script = ''
      ${pkgs.podman}/bin/podman network exists media-network || \
      ${pkgs.podman}/bin/podman network create media-network
    '';
  };

  virtualisation.oci-containers = {
    backend = "podman";
    
    containers = {
      gluetun = {
        image = "qmcgaw/gluetun";
        autoStart = true;
        extraOptions = [
          "--cap-add=NET_ADMIN"
          "--device=/dev/net/tun:/dev/net/tun"
          "--health-cmd=exit 0"
          "--network=media-network"
        ];
        environmentFiles = [
          config.sops.secrets.gluetun-env.path
          # WIREGUARD_PRIVATE_KEY
        ];
        environment = {
          VPN_SERVICE_PROVIDER = "protonvpn";
          VPN_TYPE = "wireguard";
          SERVER_COUNTRIES = "Netherlands";
          VPN_PORT_FORWARDING = "on";
          PORT_FORWARD_ONLY = "on";
          VPN_PORT_FORWARDING_UP_COMMAND = "/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data \"json={\\\"listen_port\\\":{{PORTS}}}\" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'";
          TZ = "America/New_York";
          UPDATER_PERIOD = "24h";
        };
        ports = [
          "9091:9091"  # transmission
          "9117:9117"  # jackett
          "8080:8080"  # qbittorrent
        ];
        volumes = [
          "/var/lib/gluetun/tmp:/tmp"
        ];
      };

      qbittorrent = {
        image = "lscr.io/linuxserver/qbittorrent:latest";
        autoStart = true;
        dependsOn = [ "gluetun" ];
        extraOptions = [
          "--network=container:gluetun"
        ];
        environment = {
          PUID = "0";
          PGID = "0";
          TZ = "America/New_York";
          WEBUI_PORT = "8080";
        };
        volumes = [
          "/var/lib/qbittorrent:/config"
          "/mnt/media/:/mnt/media/"
        ];
      };

      transmission_novpn = {
        image = "lscr.io/linuxserver/transmission:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        environment = {
          PUID = "0";
          PGID = "0";
          TZ = "America/New_York";
        };
        ports = [
          "9092:9091"
          "51413:51413"
          "51413:51413/udp"
        ];
        volumes = [
          "/var/lib/transmission_novpn:/data"
          "/var/lib/transmission_novpn/config:/config"
          "/mnt/media:/mnt/media"
        ];
      };

      prowlarr = {
        image = "lscr.io/linuxserver/prowlarr:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        environment = {
          PUID = "0";
          PGID = "0";
          TZ = "America/New_York";
        };
        ports = [
          "9696:9696"
        ];
        volumes = [
          "/var/lib/prowlarr/config:/config"
        ];
      };

      jackett = {
        image = "lscr.io/linuxserver/jackett:latest";
        autoStart = true;
        dependsOn = [ "gluetun" ];
        extraOptions = [
          "--network=container:gluetun"
        ];
        environment = {
          PUID = "0";
          PGID = "0";
          TZ = "America/New_York";
          AUTO_UPDATE = "true";
          RUN_OPTS = "";
        };
        volumes = [
          "/var/lib/jackett/config:/config"
          "/var/lib/jackett/blackhole:/downloads"
        ];
      };

      flaresolverr = {
        image = "ghcr.io/flaresolverr/flaresolverr:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        environment = {
          LOG_LEVEL = "info";
        };
        ports = [
          "8191:8191"
        ];
      };

      sonarr = {
        image = "lscr.io/linuxserver/sonarr:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        environment = {
          PUID = "0";
          PGID = "0";
          TZ = "America/New_York";
        };
        ports = [
          "8989:8989"
        ];
        volumes = [
          "/var/lib/sonarr/config:/config"
          "/mnt/media:/mnt/media"
        ];
      };

      radarr = {
        image = "lscr.io/linuxserver/radarr:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        environment = {
          PUID = "0";
          PGID = "0";
          TZ = "America/New_York";
        };
        ports = [
          "7878:7878"
        ];
        volumes = [
          "/var/lib/radarr/config:/config"
          "/mnt/media:/mnt/media"
        ];
      };

      bazarr = {
        image = "lscr.io/linuxserver/bazarr:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        environment = {
          PUID = "0";
          PGID = "0";
          TZ = "America/New_York";
        };
        ports = [
          "6767:6767"
        ];
        volumes = [
          "/var/lib/bazarr/config:/config"
          "/mnt/media:/mnt/media"
        ];
      };

      pinchflat = {
        image = "ghcr.io/kieraneglin/pinchflat:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        environment = {
          TZ = "America/New_York";
        };
        ports = [
          "8945:8945"
        ];
        volumes = [
          "/var/lib/pinchflat:/config"
          "/mnt/media/web:/downloads"
        ];
      };

      huntarr = {
        image = "ghcr.io/plexguide/huntarr:latest";
        autoStart = true;
        extraOptions = [
          "--network=media-network"
        ];
        ports = [
          "9705:9705"
        ];
        volumes = [
          "/var/lib/huntarr:/config"
        ];
        environment = {
          TZ = "America/New_York";
        };
      };

      unpackerr = {
        image = "golift/unpackerr";
        autoStart = true;
        user = "0:0";
        extraOptions = [
          "--security-opt=no-new-privileges:true"
          "--network=media-network"
        ];
        environmentFiles = [
          config.sops.secrets.unpackerr-env.path
          # UN_SONARR_0_API_KEY
          # UN_RADARR_0_API_KEY
        ];
        environment = {
          TZ = "America/New_York";
          UN_DEBUG = "false";
          UN_LOG_FILE = "";
          UN_LOG_FILES = "10";
          UN_LOG_FILE_MB = "10";
          UN_INTERVAL = "2m";
          UN_START_DELAY = "1m";
          UN_RETRY_DELAY = "5m";
          UN_MAX_RETRIES = "3";
          UN_PARALLEL = "1";
          UN_FILE_MODE = "0644";
          UN_DIR_MODE = "0755";
          # Sonarr Config
          UN_SONARR_0_URL = "http://sonarr:8989";
          UN_SONARR_0_PATHS_0 = "/mnt/media/downloads";
          UN_SONARR_0_PROTOCOLS = "torrent";
          UN_SONARR_0_TIMEOUT = "10s";
          UN_SONARR_0_DELETE_ORIG = "false";
          UN_SONARR_0_DELETE_DELAY = "5m";
          # Radarr Config
          UN_RADARR_0_URL = "http://radarr:7878";
          UN_RADARR_0_PATHS_0 = "/mnt/media/downloads";
          UN_RADARR_0_PROTOCOLS = "torrent";
          UN_RADARR_0_TIMEOUT = "10s";
          UN_RADARR_0_DELETE_ORIG = "false";
          UN_RADARR_0_DELETE_DELAY = "5m";
        };
        volumes = [
          "/mnt/media/downloads:/mnt/media/downloads"
        ];
      };
    };
  };

  system.stateVersion = "25.05";
}
