{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.mount_media.enable = true;

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;

  services.jellyfin = {
    enable = true;
    package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.jellyfin;
    openFirewall = true;
  };

  networking.firewall.allowedTCPPorts = [ 8000 ];
  

  system.stateVersion = "25.05";
}