{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  sops = {
      # defaultSopsFile = ../../../secrets/secrets.yaml;
      secrets = {
        "onlyoffice-jwt-secret" = {};
      };
    };

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;

  services.onlyoffice = {
    enable = true;
    hostname = "theoffice.montycasa.com";
    jwtSecretFile = config.sops.secrets."onlyoffice-jwt-secret".path;
  };

  networking.firewall.allowedTCPPorts = [ 8000 ];

  system.stateVersion = "25.05";
}