{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  sops = {
      # defaultSopsFile = ../../../secrets/secrets.yaml;
      secrets = {
        "onlyoffice-jwt-secret" = {
          owner = "onlyoffice";
          group = "onlyoffice";
          mode = "0400";
          
          # Restart the service when the secret changes
          restartUnits = [ "onlyoffice-docservice.service" ];
        };
      };
    };

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;

  services.onlyoffice = {
    enable = true;
    hostname = "theoffice.montycasa.com";
    jwtSecretFile = config.sops.secrets."onlyoffice-jwt-secret".path;
    # postgresHost = "localhost"; 
  };

  services.nginx = {
    enable = true;
    recommendedProxySettings = true;
    
    virtualHosts."theoffice.montycasa.com" = {
      locations."/" = {
        proxyPass = "http://localhost:8000";
        proxyWebsockets = true;
        extraConfig = ''
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
        '';
      };
    };
  };
  
  networking.firewall.allowedTCPPorts = [ 80 443 8000 ];

  # networking.firewall.allowedTCPPorts = [ 8000 ];

  system.stateVersion = "25.05";
}