{ pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  
  services.openssh.enable = true;

  services.onlyoffice = {
    enable = true;
    hostname = "theoffice.montycasa.com";
  };

  networking.firewall.allowedTCPPorts = [ 80 ];

  system.stateVersion = "25.05";
}