{ config, pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  extra-services.tailscale = {
    enable = true;
    lxc = true;
  };
  extra-services.host-checkin.enable = true;

  services.openssh.enable = true;

  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  users.users.netalertx = {
    isSystemUser = true;
    group = "netalertx";
    uid = 20211;
  };

  users.groups.netalertx = {
    gid = 20211;
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/netalertx 0755 netalertx netalertx -"
    "d /var/lib/netalertx/db 0755 netalertx netalertx -"
    "d /var/lib/netalertx/config 0755 netalertx netalertx -"
  ];

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      netalertx = {
        image = "ghcr.io/jokob-sk/netalertx:25.11";
        autoStart = true;
        extraOptions = [
          "--network=host"
          "--cap-drop=ALL"
          "--cap-add=NET_ADMIN"
          "--cap-add=NET_RAW"
          "--cap-add=NET_BIND_SERVICE"
          "--cap-add=CHOWN"
          "--cap-add=SETUID"
          "--cap-add=SETGID"
          "--read-only"
          # TODO...
          #"--tmpfs=/tmp:uid=20211,gid=20211,mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"
          # "--memory=2048m"
          # "--memory-reservation=1024m"
          # "--cpus=0.5"
          # "--pids-limit=512"
        ];
        volumes = [
          "/var/lib/netalertx:/data"
          "/etc/localtime:/etc/localtime:ro"
        ];
        environment = {
          LISTEN_ADDR = "0.0.0.0";
          PORT = "20211";
          GRAPHQL_PORT = "20212";
          ALWAYS_FRESH_INSTALL = "false";
          NETALERTX_DEBUG = "0";
        };
      };
    };
  };

  # Configure VLAN interfaces
  networking.interfaces.eth1.ipv4.addresses = [{
    address = "192.168.10.100";
    prefixLength = 24;
  }];

  networking.interfaces.eth2.ipv4.addresses = [{
    address = "192.168.20.100";
    prefixLength = 24;
  }];

  networking.firewall = {
    allowedTCPPorts = [20211 20212];
  };

  virtualisation.podman.autoPrune = {
    enable = true;
    flags = ["--all"];
  };

  system.stateVersion = "25.11";
}