{ config, pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
    # ../../secrets
  ];

  environment.systemPackages = with pkgs; [
    
  ];

  extra-services.tailscale = {
    enable = true;
    userspace-networking = true;
  };
  
  services.openssh.enable = true;

  services.pocket-id = {
    enable = true;
    # package = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system}.pocket-id;
    settings = {
      APP_URL = https://auth2.montycasa.com;
      ANALYTICS_DISABLED = true;
      PORT = "1411";
    };
  };

  networking.firewall.allowedTCPPorts = [ 8000 ];
  

  system.stateVersion = "25.05";
}